Visual and Style Fixes
acmucsd/acm-ai-site pull request #136
Opened 2024-07-29 07:26 UTC by angelatsai1214

Finish issue #114 

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/6f9d5b0d-15fc-4471-b3f2-46974d3d4805">

- made the Login button bolder so looks about the same size as the rest of the navbar text
- added gradient bar to non-main-pages
- made the cards in projects page all the same height, if description overflows, then the card is scrollable
- as well as address the changes needed from the issue

2024-07-30 06:27 UTC, sprestrelski requested changes

2024-07-30 06:27 UTC, sprestrelski commented on src/components/ProjectCard/index.less
I'm not sure about the responsiveness of this. Might be better to follow [devpost's style](https://devpost.com/software) of limiting the title and description text instead? 
![image](https://github.com/user-attachments/assets/e0187443-7f6f-4b59-84db-2cff18d007ed)

2024-07-30 06:27 UTC, sprestrelski commented on src/components/MainFooter/index.tsx
if the footer has the gradient bar added, why is the gradient also added directly in EventsPage/index.tsx?

2024-07-30 06:27 UTC, sprestrelski commented on src/pages/MainPage/index.tsx
I think we can leave out the UC San Diego for now as it's very visually unbalanced. We can redo the splash page during the homepage redesign
![image](https://github.com/user-attachments/assets/8cfd337f-bcf1-46b9-b3c2-02c175e664d4)

2024-08-11 17:01 UTC, angelatsai1214 commented on src/components/MainFooter/index.tsx
MainFooter component  <MainFooter isMainPage={false}/> was not used for EventsPage which I think is because the Events Page has some customized content they are displaying at the footer, while all the rest of the pages use the same content for the footer, do you want me to change so that the MainFooter would take in parameter for the content of the footer?

2024-08-11 22:55 UTC, sprestrelski commented on src/components/MainFooter/index.tsx
hmm can we move the events page footer info to a different format (similar to the homepage) and add the MainFooter? that way we can standardize the footer component across the site
![image](https://github.com/user-attachments/assets/273617d7-df51-4b41-b368-1ddf456140b3)

2025-02-03 19:14 UTC, sprestrelski commented on src/components/ProjectCard/index.less
won't change for now

2025-02-03 19:27 UTC, sprestrelski approved these changes
fixed merge conflicts

notes for later:
- projects cards could still be improved
- improve text wrapping for long event names
![image](https://github.com/user-attachments/assets/2dfcc445-2175-4467-8734-31b8a4cc618d)

2025-02-03 19:27 UTC, merged